allow multiple directories, even *
git-svn-id: http://svn.code.sf.net/p/cgns/code/CGNS_docs_current@276 59ee3124-ab72-4556-8a47-5b88dfbcc004

diff --git a/makehtml b/makehtml
--- a/makehtml
+++ b/makehtml
@@ -9,56 +9,73 @@
 
 version='1.0, 8 June 2001'
 
-usage='USAGE: makehtml directory'
+usage='USAGE: makehtml dirlist'
 
-# Check for specified directory
-if [ $# -eq 0 ]
-then
-   echo 'Error: No directory specified' >& 2
+# get the directories to process
+
+dirs=""
+while [ $# -gt 0 ]; do
+  [ -d $1 ] && dirs="$dirs $1"
+  shift
+done
+
+if [ -z "$dirs" ]; then
+   echo 'Error: No directories specified' >& 2
    echo $usage >& 2
    exit 1
 fi
 
-# Set directory name
-directory=$1
+# process the directories
 
-# Check for valid directory
-if [ ! -d $directory ]
-then
-   echo "Error: Directory $directory doesn't exist" >& 2
-   exit 1
-fi
+for d in $dirs ; do
+
+# Set directory name
+  directory=$d
 
 # Create the tar file
-case $directory in
-   adf)          tar cvf adf.tar \
-                     adf/adf.css adf/*html adf/*.gif;;
-   cgnstools)    tar cvf cgnstools.tar \
-                     cgnstools/cgnstools.css cgnstools/index.html cgnstools/adfviewer cgnstools/cgnsplot cgnstools/utilities ;;
-   charter)      tar cvf charter.tar \
-                     charter/charter.css charter/*html;;
-   filemap)      tar cvf filemap.tar \
-                     filemap/filemap.css filemap/*html filemap/figures;;
-   filemap_hdf)  tar cvf filemap_hdf.tar \
-                     filemap_hdf/filemap_hdf.css filemap_hdf/*html filemap_hdf/figures;;
-   logo)         tar cvf logo.tar \
-                     logo/cgns*;;
-   midlevel)     tar cvf midlevel.tar \
-                     midlevel/midlevel.css midlevel/*html;;
-   overview)     tar cvf overview.tar \
-                     overview/overview.css overview/*html;;
-   sids)         tar cvf sids.tar \
-                     sids/sids.css sids/*html sids/*eqs sids/*figs;;
-   user)         tar cvf user.tar \
-                     user/user.css user/*html user/figures;;
-esac
+# explicitly name the files so don't get .svn
+  case $d in
+    adf)          tar cvf adf.tar \
+                      adf/adf.css adf/*.html adf/*.gif adf/*.png;;
+    cgio)         tar cvf cgio.tar \
+                     cgio/cgio.css cgio/*.html cgio/*.gif cgio/*.png;;
+    cgnstools)    tar cvf cgnstools.tar \
+                      cgnstools/cgnstools.css cgnstools/*.html cgnstools/*.png \
+                      cgnstools/cgnsplot/*.html cgnstools/cgnsplot/*.png \
+                      cgnstools/cgnsplot/images/*.html cgnstools/cgnsplot/images/*.gif \
+                      cgnstools/cgnsview/*.html cgnstools/cgnsview/images/*.gif \
+                      cgnstools/utilities/*.html cgnstools/utilities/*.png \
+                      cgnstools/utilities/images/*.html cgnstools/utilities/images/*.gif;;
+    charter)      tar cvf charter.tar \
+                      charter/charter.css charter/*.html charter/*.png;;
+    filemap)      tar cvf filemap.tar \
+                      filemap/filemap.css filemap/*.html filemap/*.png \
+                      filemap/figures/*.html filemap/figures/*.gif;;
+    hdf5)         tar cvf hdf5.tar \
+                      hdf5/hdf5.css hdf5/*.html hdf5/*.png;;
+    logo)         tar cvf logo.tar \
+                      logo/cgns*;;
+    midlevel)     tar cvf midlevel.tar \
+                      midlevel/midlevel.css midlevel/*.html midlevel/*.png;;
+    overview)     tar cvf overview.tar \
+                      overview/overview.css overview/*.html overview/*.png;;
+    sids)         tar cvf sids.tar \
+                      sids/sids.css sids/*.html sids/*.png \
+                      sids/*.eqs/*.html sids/*.eqs/*.gif \
+                      sids/*.figs/*.html sids/*.figs/*.gif;;
+    user)         tar cvf user.tar \
+                      user/user.css user/*.html user/*.png \
+                      user/figures/*.html user/figures/*.gif;;
+    *)            directory=""
+                  echo "skipping directory $d" ;;
+  esac
 
+  if [ -n "$directory" ]; then
 # Compress it, show the sizes, and move it into the directory
-gzip $directory.tar
-gzip -l $directory.tar.gz
-if [ $directory != minutes -a $directory != papers -a $directory != slides ]
-then
-   mv $directory.tar.gz $directory
-fi
+    gzip $directory.tar
+    gzip -l $directory.tar.gz
+    mv $directory.tar.gz $directory
+    echo "$directory.tar.gz - done"
+  fi
 
-echo "$directory.tar.gz - done"
+done
